spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: cms@demo
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true